name: Backup Firestore

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  
env:
  PROJECT_ID: firebase-0nk01n
  BUCKET: gs://backup-whole-database
  
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - run: gcloud info
    - run: gcloud config set project $PROJECT_ID
    - run: gcloud firestore export $BUCKET
