name: Backup Firestore

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  PROJECT_ID: firebase-0nk01n
  BUCKET: gs://backup-whole-database
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
  
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.firebase-0nk01n }}  # Set the project ID
    - run: gcloud info
    - run: gcloud config set project $PROJECT_ID
    - run: gcloud firestore export $BUCKET
